Feature
lirad/ruby-enumerable-methods pull request #2
Opened 2020-08-24 14:00 UTC by AkintoyeOlamide

2020-08-24 15:40 UTC, mikenath223 requested changes
### Hi Team 👋

Nice work so far, however, let's fix this:

- [ ] Kindly update your readme to reflect the present project as it presently refers to bubble_sort rather than enumerables.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-08-24 15:40 UTC, mikenath223 commented on enumerable.rb
> +    if obj.nil?
- [ ] my_all, when no block or argument is given, should return false if any of the array elements passed is false yours returns true.

2020-08-24 15:45 UTC, mikenath223 commented on enumerable.rb
> +    if obj.nil?
- [x] my_any, when no block or argument is passed, should return false if at least one of the array elements is not true.

- [x] Also if a class is passed should return the right result.

2020-08-24 15:47 UTC, mikenath223 commented on enumerable.rb
> +    if obj.nil?
- [ ] my_none, when no block or argument is passed, should return false if one of the array elements is true.

- [ ] Also if a class is passed should return the right result.

- [ ] Yours throws an error of `wrong argument type Integer (expected Regexp)` in a case like this `array_of_words.my_none?(5)`.

2020-08-24 15:49 UTC, mikenath223 commented on enumerable.rb
> +      my_each { |_i| counter += 1 }
- [ ] Should count the number of items in enum that equal to the item passed in the argument. Yours doesn't count.

2020-08-24 15:50 UTC, mikenath223 commented on enumerable.rb
> +    my_each do |i|
- [ ] my_map should execute only the proc when both a block and a proc are passed and return a new array. Yours returns the wrong result kindly fix it.

2020-08-24 15:55 UTC, mikenath223 commented on enumerable.rb
> +      n.times do |i|
- [ ] my_inject is expected to raise a LocalJumpError when no block or argument is given.

- [ ] It should be able to search for the longest word in an array of words. Yours throws an error of undefined method length.

- [ ] It fails also in a case like this `range.my_inject(4) { |prod, n| prod * n}`

- It seems my_inject wasn't structured to take a range. Kindly include this feature.

2020-08-25 17:48 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- There are several syntax errors in your file on lines -> 58, 62, 64. These are the errors 👇:

  ![image](https://user-images.githubusercontent.com/57726348/91208584-09f54b00-e728-11ea-8b0c-34aa1eba86b8.png)

- Please fix all rubocop errors before requesting for code review.

- Your README is from a different project - Bubble Sort. Please update it. This has also been pointed out by the previous reviewer.

_You will find additional comments below._

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-08-25 17:48 UTC, tirthajyoti-ghosh commented on enumerable.rb
> +    return if false obj.nil? && !block_given?
This line throws an error:

`unexpected tIDENTIFIER, expecting end`

2020-08-25 17:48 UTC, tirthajyoti-ghosh commented on enumerable.rb
> +      my_each { |i| break result = unless yield(i) }
Syntax error: `unexpected '}', expecting then or ';' or '\n'`

2020-08-25 17:48 UTC, tirthajyoti-ghosh commented on enumerable.rb
> +      my_each { |i| break result = unless i.match?(obj) }
Syntax error: `unexpected '}', expecting then or ';' or '\n'`

2020-08-25 17:48 UTC, tirthajyoti-ghosh commented on enumerable.rb
> +      raise('LocalJumpError') if !block_given? && obj.nil?
Repeating function definition. You have defined the `my_inject` function twice. Please remove one.

2020-08-26 06:59 UTC, lekegitrepo approved these changes
### Status: Approve :heavy_check_mark:
#### Hi @AkintoyeOlamide and @lirad :clap: :clap:
#### You have done a good job. All the syntax errors are fixed as required in the last review.
#### This project is approved, you can merge it now.

#### _Reviewed by Temitayo Adeleke_.

2020-08-26 07:23 UTC, merged