Testing Your Ruby Code - Enumerable
lirad/ruby-enumerable-methods pull request #5
Opened 2020-09-10 15:53 UTC by lirad

-Installed Rspec
-Initialized Rspec and created a file for testing methods
-Added test cases to all methods
-Updated readme file

2020-09-10 18:26 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### You have done a good job :muscle:
#### 79 test cases, 68 pass :heavy_check_mark: and 11 fail :x:
#### Check my inline comments below and the comments I added here due to some comment glitch I was unable to add it directly to the affected section of the code.

- **_`#my_any?` when no block or argument is given returns true if at least one of the collection is not false or nil_**

- **_`#my_any?` when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric_**

- **_`#my_any?` when a Regex is passed as an argument returns true if any of the collection matches the Regex_**

- **_`#my_none?` when no block or argument is given returns true only if none of the collection members is true_**

- **_`#my_none?` when a Regex is passed as an argument returns false if any of the collection matches the Regex_**

**_Kindly fix these and submit them for review._**

#### _Reviewed by Temitayo Adeleke._

2020-09-10 18:26 UTC, lekegitrepo commented on enumerable.rb
>    def my_all?(obj = nil)
- **_`#my_all?` when no block or argument is given returns true when none of the collection members are false or nil_**

- **_`#my_all?` when a class is passed as an argument returns false if any of the collection is not a member of such class_**

- **_`#my_all?` when a Regex is passed as an argument returns false if any of the collection does not match the Regex_**

2020-09-10 18:26 UTC, lekegitrepo commented on enumerable.rb
> +  def my_map(_obj = nil)
- **_`#my_map` executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum._**

2020-09-10 18:26 UTC, lekegitrepo commented on enumerable.rb
>  end
- **_`#my_inject` raises a "LocalJumpError" when no block or argument is given_**

2020-09-10 18:26 UTC, lekegitrepo commented on enumerable.rb
>  end
- **_`#multiply_els` accepts an array as an argument and multiplies all the elements of the array together using #my_inject_**

2020-09-10 18:34 UTC, lirad commented
Hello @lekegitrepo, how are you? I just got your review on testing my ruby enumerable code but no remarks were made in the testing file. Just want to make sure I still have to work on the enumerates or if I should work on the test cases. Best,

2020-09-11 15:22 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for applying the suggested changes.
However there are sill some issues to solve

1. I tweak a bit your tests and add some tests. They all failed. Read the comments below.

2. Add tests for `my_all?`, `my_any?`, `my_none?` for testing **String**, _**Integer**,_ **Regex**. Check also if the array is empty or contains the same values.

3. Please, expect `false` and `true`. Switch between the two. Test a method were the result will be **true** and somewhere else where the result will be **false**

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-09-11 15:22 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
```rb


    it 'twist it a bit - 1' do
      true_array = [1, true, 'hi', []]
      expect(true_array.my_all?).eq(true_array.all?)

      false_array = [1, false, 'hi', []]
      expect(false_array.my_all?).eq(false_array.all?)
    end
```

2020-09-11 15:22 UTC, maelfosso commented on spec/enumerables_spec.rb
> +      result = array_strings.my_all?(array_strings)
No added values. Change it please.

2020-09-11 15:22 UTC, maelfosso commented on spec/enumerables_spec.rb
> +    end
```rb
it 'twist it a bit - 2' do
      true_array = [nil, false, true, []]
      expect(true_array.my_any?).eq(true_array.any?)

      false_array = [nil, false, nil, false]
      expect(false_array.my_any?).eq(false_array.any?)
    end
```

2020-09-11 15:22 UTC, maelfosso commented on spec/enumerables_spec.rb
> +    end
```rb
it 'twist it a bit - 3' do
      true_array = [nil, false, true, []]
      expect(true_array.my_none?).eq(true_array.none?)

      false_array = [nil, false, nil, false]
      expect(false_array.my_none?).eq(false_array.none?)
    end
```

2020-09-12 00:03 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] Let's work on all changes required by @maelfosso 
- [ ] Lets test for when a class is passed as an argument.
- [ ] Please, expect false and true. Switch between the two. Test a method were the result will be true and somewhere else where the result will be false .**As Requested by the previous TSE**
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-13 20:02 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-13 20:02 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +      result = array_integers.my_all?(array_integers.all?)
You are calling the main enumerable method inside yours as an argument isn't proper.
 `array_integers.my_all?(array_integers.all?)`
- [ ] You could check for when a block is given.



**Note:** Lets apply this to all `it` block in this scenario

2020-09-13 21:58 UTC, elmejdki requested changes
# status: require changes :recycle: 

### Please work on the previously required changes before you submit another code review

2020-09-13 23:30 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Hi, it's me again, Great job thank you for making the required changes.

now you can merge, your project is approved :heavy_check_mark: 

## Happy Coding :tophat:

2020-09-13 23:37 UTC, merged